<h1 align="center"><b>Create  – Dataset for User<b></h1>
<h1 align="center">
    <a href="https://si3.ufc.br/sigaa/portais/discente/discente.jsf">Davi, Kelvin e Wesley</a>
</h1>
<h1 align="center">
    <a href="https://www.sidi.org.br/"> Projeto SiDi</a>
</h1>

<a href="https://github.com/daviolp/">
<img src="https://img.shields.io/static/v1?label=GitHub&message=daviolp&color=7159c1&style=for-the-badge&logo=ghost"/>
<a href="https://github.com/kelvin-ksl">
<img src="https://img.shields.io/static/v1?label=GitHub&message=Kelvin&color=7159c1&style=for-the-badge&logo=ghost"/>
<a href="https://github.com/wesleypavanello">
<img src="https://img.shields.io/static/v1?label=GitHub&message=Wesley&color=7159c1&style=for-the-badge&logo=ghost"/>

In [1]:
import pandas as pd
from json_normalize import json_normalize
from datetime import datetime
from functools import reduce
from pytz import timezone
import json
import pytz
import os

In [2]:
with open('TestSet_Task1_keystroke_enrolment.json') as f1:
      data1 = json.load(f1)

In [3]:
df1 = pd.DataFrame(data1)
df_series1 = df1.squeeze()

In [4]:
df_series1.index[[0]][0]

'enrolment_gqxZ'

In [5]:
vet1 = []
vet2 = []
vet3 = []
vet4 = []
vet5 = []
vet6 = []

vet1.clear()
vet2.clear()
vet3.clear()
vet4.clear()
vet5.clear()
vet6.clear()

In [6]:
for i in df_series1.index[[0]]:
    print(i)
    index = df_series1[i]
    for linha in range(0, len(index['sensor_acc'])):
        pos1_sensor_acc = index['sensor_acc'][linha][0]
        pos2_sensor_acc = index['sensor_acc'][linha][1]
        pos3_sensor_acc = index['sensor_acc'][linha][2]
        pos4_sensor_acc = index['sensor_acc'][linha][3]
        
        #mostrando que pegou apenas um usuário
        user = df_series1.index[[0]][0]
        
        #criando o dicionario e passando para o vetor para ser criado o dataframe
        dicio_sensor_acc = {'sensor_acc': user, 'timestamp': pos1_sensor_acc, 'x_coordinate_sensor_acc': pos2_sensor_acc,'y_coordinate_sensor_acc': pos3_sensor_acc, 'z_coordinate_sensor_acc': pos4_sensor_acc}
        
        vet1.append(dicio_sensor_acc)
    
    for linha2 in range(0, len(index['sensor_grav'])):
        pos1_sensor_grav = index['sensor_grav'][linha2][0]
        pos2_sensor_grav = index['sensor_grav'][linha2][1]
        pos3_sensor_grav = index['sensor_grav'][linha2][2]
        pos4_sensor_grav = index['sensor_grav'][linha2][3]
        
        #mostrando que pegou apenas um usuário
        user = df_series1.index[[0]][0]
        
        dicio_sensor_grav = {'sensor_grav': user, 'timestamp': pos1_sensor_grav, 'x_coordinate_sensor_grav': pos2_sensor_grav,'y_coordinate_sensor_grav': pos3_sensor_grav, 'z_coordinate_sensor_grav': pos4_sensor_grav}
        
        vet2.append(dicio_sensor_grav)
    

    for linha3 in range(0, len(index['sensor_gyro'])):
        pos1_sensor_gyro = index['sensor_gyro'][linha3][0]
        pos2_sensor_gyro = index['sensor_gyro'][linha3][1]
        pos3_sensor_gyro = index['sensor_gyro'][linha3][2]
        pos4_sensor_gyro = index['sensor_gyro'][linha3][3]
         
        #mostrando que pegou apenas um usuário
        user = df_series1.index[[0]][0]
        
        dicio_sensor_gyro = {'sensor_gyro': user, 'timestamp': pos1_sensor_gyro, 'x_coordinate_sensor_gyro': pos2_sensor_gyro,'y_coordinate_sensor_gyro': pos3_sensor_gyro, 'z_coordinate_sensor_gyro': pos4_sensor_gyro}
        
        vet3.append(dicio_sensor_gyro)

    for linha4 in range(0, len(index['sensor_accl'])):
        pos1_sensor_accl = index['sensor_accl'][linha4][0]
        pos2_sensor_accl = index['sensor_accl'][linha4][1]
        pos3_sensor_accl = index['sensor_accl'][linha4][2]
        pos4_sensor_accl = index['sensor_accl'][linha4][3]
         
        #mostrando que pegou apenas um usuário
        user = df_series1.index[[0]][0]
        
        dicio_sensor_accl = {'sensor_accl': user, 'timestamp': pos1_sensor_accl, 'x_coordinate_sensor_accl': pos2_sensor_accl,'y_coordinate_sensor_accl': pos3_sensor_accl, 'z_coordinate_sensor_accl': pos4_sensor_accl}
        
        vet4.append(dicio_sensor_accl)     
    
    for linha5 in range(0, len(index['sensor_magn'])):
        pos1_sensor_magn = index['sensor_magn'][linha5][0]
        pos2_sensor_magn = index['sensor_magn'][linha5][1]
        pos3_sensor_magn = index['sensor_magn'][linha5][2]
        pos4_sensor_magn = index['sensor_magn'][linha5][3]
         
        #mostrando que pegou apenas um usuário
        user = df_series1.index[[0]][0]
        
        dicio_sensor_magn = {'sensor_magn': user,'timestamp': pos1_sensor_magn, 'x_coordinate_sensor_magn': pos2_sensor_magn,'y_coordinate_sensor_magn': pos3_sensor_magn, 'z_coordinate_sensor_magn': pos4_sensor_magn}
        
        vet5.append(dicio_sensor_magn)    

    for linha6 in range(0, len(index['touch'])):
        #parte do sensor de touch
        pos1_sensor_touch = index['touch'][linha6][0]
        pos2_sensor_touch = index['touch'][linha6][1]
        
        #mostrando que pegou apenas um usuário
        user = df_series1.index[[0]][0]
        
        dicio_sensor_touch = {'touch': user, 'timestamp': pos1_sensor_touch, 'ascii_code_touch': pos2_sensor_touch}
    
        vet6.append(dicio_sensor_touch)

enrolment_gqxZ

In [7]:
df_sensor_acc_one_user = pd.DataFrame(vet1)
df_sensor_acc_one_user.drop(columns='sensor_acc',inplace=True)
df_sensor_acc_one_user

,timestamp,x_coordinate_sensor_acc,y_coordinate_sensor_acc,z_coordinate_sensor_acc
0,50186983937572,-1.0475,8.4443,4.8978
1,50186983967311,-1.0570,8.4419,4.8835
2,50186983997832,-1.0810,8.4395,4.9074
3,50186984078041,-1.1073,8.4323,4.9361
4,50186984123041,-1.1097,8.4419,4.9481
...,...,...,...,...
27546,50322892385905,0.2500,8.4921,5.2783
27547,50322892410124,0.2644,8.4802,5.2639
27548,50322892437051,0.2764,8.4969,5.2639
27549,50322892459603,0.2859,8.4849,5.2496
27550,50322892487103,0.2764,8.4682,5.2232

In [8]:
df_sensor_grav_one_user = pd.DataFrame(vet2)
df_sensor_grav_one_user.drop(columns='sensor_grav',inplace=True)
df_sensor_grav_one_user.head()

,timestamp,x_coordinate_sensor_grav,y_coordinate_sensor_grav,z_coordinate_sensor_grav
0,50186983954395,-1.0807,8.3306,5.0601
1,50186983986530,-1.0802,8.3322,5.0574
2,50186984009239,-1.0799,8.3338,5.0550
3,50186984095801,-1.0798,8.3350,5.0529
4,50186984132572,-1.0798,8.3361,5.0512

In [9]:
df_sensor_gyro_one_user = pd.DataFrame(vet3)
df_sensor_gyro_one_user.drop(columns='sensor_gyro',inplace=True)
df_sensor_gyro_one_user.head()

,timestamp,x_coordinate_sensor_gyro,y_coordinate_sensor_gyro,z_coordinate_sensor_gyro
0,50186983918822,0.0377,0.0002,0.0049
1,50186983961218,0.0316,-0.0047,0.0024
2,50186983992311,0.0255,-0.0072,-0.0012
3,50186984071061,0.0206,-0.0108,-0.0037
4,50186984119082,0.0170,-0.0121,-0.0024

In [10]:
df_sensor_accl_one_user = pd.DataFrame(vet4)
df_sensor_accl_one_user.drop(columns='sensor_accl',inplace=True)
df_sensor_accl_one_user.head()

,timestamp,x_coordinate_sensor_accl,y_coordinate_sensor_accl,z_coordinate_sensor_accl
0,50186983947103,0.0376,0.0777,-0.1827
1,50186983980801,0.0371,0.0787,-0.1799
2,50186984003405,0.0272,0.0750,-0.1917
3,50186984089811,0.0031,0.0715,-0.1656
4,50186984129291,-0.0233,0.0634,-0.1351

In [11]:
df_sensor_magn_one_user = pd.DataFrame(vet5)
df_sensor_magn_one_user.drop(columns='sensor_magn',inplace=True)
df_sensor_magn_one_user.head()

,timestamp,x_coordinate_sensor_magn,y_coordinate_sensor_magn,z_coordinate_sensor_magn
0,50186983974395,18.8250,-24.8063,-17.4188
1,50186984083718,16.5000,-24.1875,-16.8375
2,50186984155801,17.7563,-24.1313,-17.8875
3,50186984211270,16.9875,-23.7375,-17.1562
4,50186984257259,19.8000,-24.2250,-16.5000

In [12]:
df_sensor_touch_one_user = pd.DataFrame(vet6)
df_sensor_touch_one_user.drop(columns='touch',inplace=True)
df_sensor_touch_one_user.head()

        timestamp  ascii_code_touch
0  50264976127386           0.08548
1  50265151152386           0.07206
2  50265310812594           0.08191
3  50265513449782           0.01399
4  50265694047021           0.07249

### ***Realizando o agrupamento e resample dos dados***

In [13]:
# Convert timestamp to datetime object and set as index
df_sensor_acc_one_user['timestamp'] = pd.to_datetime(df_sensor_acc_one_user['timestamp'])#, unit='us') 
df_sensor_grav_one_user['timestamp'] = pd.to_datetime(df_sensor_grav_one_user['timestamp'])#, unit='us')
df_sensor_gyro_one_user['timestamp'] = pd.to_datetime(df_sensor_gyro_one_user['timestamp'])#, unit='us')
df_sensor_accl_one_user['timestamp'] = pd.to_datetime(df_sensor_accl_one_user['timestamp'])#, unit='us')
df_sensor_magn_one_user['timestamp'] = pd.to_datetime(df_sensor_magn_one_user['timestamp'])#, unit='us')
df_sensor_touch_one_user['timestamp'] = pd.to_datetime(df_sensor_touch_one_user['timestamp'])#, unit='us')


# Set index of columns
df_sensor_acc_one_user.set_index('timestamp', inplace=True)
df_sensor_grav_one_user.set_index('timestamp', inplace=True)
df_sensor_gyro_one_user.set_index('timestamp', inplace=True)
df_sensor_accl_one_user.set_index('timestamp', inplace=True)
df_sensor_magn_one_user.set_index('timestamp', inplace=True)
df_sensor_touch_one_user.set_index('timestamp', inplace=True)

# Exemple resample (2S), miliseconds (100L), Micro (100000us) and Nano (100000000N)
# Resample to a frequency of 100 milliseconds and calculate rolling mean with window of 10 samples

df_sensor_acc_one_user = df_sensor_acc_one_user.resample('100L').mean().rolling(window=10).mean()
df_sensor_grav_one_user = df_sensor_grav_one_user.resample('100L').mean().rolling(window=10).mean()
df_sensor_gyro_one_user = df_sensor_gyro_one_user.resample('100L').mean().rolling(window=10).mean()
df_sensor_accl_one_user = df_sensor_accl_one_user.resample('100L').mean().rolling(window=10).mean()
df_sensor_magn_one_user = df_sensor_magn_one_user.resample('100L').mean().rolling(window=10).mean()
df_sensor_touch_one_user = df_sensor_touch_one_user.resample('100L').mean().rolling(window=10).mean()


data_frames = [df_sensor_acc_one_user, df_sensor_grav_one_user, df_sensor_gyro_one_user, df_sensor_accl_one_user,
               df_sensor_magn_one_user, df_sensor_touch_one_user]

# Merge DataFrames
df_merged = reduce(lambda left,right: pd.merge(left,right , left_index=True, right_index=True), data_frames)

# Reset index
df_merged.reset_index(inplace=True)

In [14]:
df_merged

,timestamp,x_coordinate_sensor_acc,y_coordinate_sensor_acc,z_coordinate_sensor_acc,x_coordinate_sensor_grav,y_coordinate_sensor_grav,z_coordinate_sensor_grav,x_coordinate_sensor_gyro,y_coordinate_sensor_gyro,z_coordinate_sensor_gyro,x_coordinate_sensor_accl,y_coordinate_sensor_accl,z_coordinate_sensor_accl,x_coordinate_sensor_magn,y_coordinate_sensor_magn,z_coordinate_sensor_magn,ascii_code_touch
0,1970-01-01 13:57:44.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970-01-01 13:57:45.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970-01-01 13:57:45.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1970-01-01 13:57:45.200,0.195426,9.144537,3.464288,0.275167,9.106765,3.552951,0.185236,-0.002130,0.006479,-0.081128,0.017734,-0.088308,11.367064,-26.881227,-21.145000,NaN
4,1970-01-01 13:57:45.300,0.211828,9.199712,3.216809,0.281487,9.183550,3.367821,0.174613,-0.002086,0.016660,-0.070976,-0.000139,-0.149386,11.344415,-27.282177,-20.591176,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,1970-01-01 13:58:37.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,1970-01-01 13:58:37.400,0.635405,9.373690,2.744650,0.636804,9.389702,2.755102,-0.024527,-0.011246,-0.019297,0.000046,0.000455,-0.007502,10.182587,-28.596138,-18.648246,NaN
526,1970-01-01 13:58:37.500,0.628883,9.366373,2.762381,0.621518,9.384556,2.775228,-0.029360,-0.003995,-0.021692,0.009408,-0.000759,-0.008450,10.277460,-28.519715,-18.614269,NaN
527,1970-01-01 13:58:37.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,1970-01-01 13:58:37.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# for dataset in range(len(dfs_windows)):
#     dfs_windows[dataset].to_csv(f'./datas_windows/dataframe{dataset}.csv', index = False)

In [16]:
df_merged.isna().sum()

timestamp                     0
x_coordinate_sensor_acc     312
y_coordinate_sensor_acc     312
z_coordinate_sensor_acc     312
x_coordinate_sensor_grav    322
y_coordinate_sensor_grav    322
z_coordinate_sensor_grav    322
x_coordinate_sensor_gyro    312
y_coordinate_sensor_gyro    312
z_coordinate_sensor_gyro    312
x_coordinate_sensor_accl    312
y_coordinate_sensor_accl    312
z_coordinate_sensor_accl    312
x_coordinate_sensor_magn    323
y_coordinate_sensor_magn    323
z_coordinate_sensor_magn    323
ascii_code_touch            529
dtype: int64

In [17]:
df_merged.to_csv("user_teste.csv", index = False)

In [18]:
# df_merged.to_csv("user1_keystroke_time_seconds_rolling_mean.csv", index = False)